# Generated by Django 3.2 on 2022-12-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(choices=[('Full_Time', 'Full_Time'), ('Part_Time', 'Part_Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], default='Full_Time', max_length=20),
        ),
    ]
